### ISSUE TITLE
[Bash on Windows support] Port already use

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/ocsigenserver#104]
I tried to use eliom on Windows with the new Bash On Windows.
The installation is ok, and compilation also. (dev and 2.7 version)

But when we want to run ocsigenserver with ```make test.byte``` we have
```
ocsigenserver  -c local/etc/test/test-test.conf
ocsigenserver: ocsigen:main: Fatal - The port 8080 is already in use.
make: *** [test.byte] Error 8
```
I don't have any other application running on port 8080, and any other port doesn't work.

I don't know how Bash On Windows works, it's just to report the issue.
I can test new version if you want.

With Bash On Windows, I think it would be a great opportunity for the OCaml community to have more success on Windows so it could be interesting to have support.

**Comment by vasilisp** [comment]
It doesn't look like the issue is on our side. If the OS says that the port is in use (`EADDRINUSE`) we can't do anything further.

Does WSL provide any means of controlling what ports you can open? On Linux under standard settings you need root permissions to listen on anything smaller than 1024. Maybe the limit is higher on Windows/WSL? Or maybe there is some kind of firewall that doesn't even let you `listen(3)`?

**Comment by dannywillems** [comment]
It was because IPV6_V6ONLY was used by default if we don't mention an IP address in the configuration file for the port.
By changing
```
<port>4500</port>
```
to
```
<port>0.0.0.0:4500</port>
```
it works.

**Comment by vasilisp** [comment]
Great, thanks for testing!

@vouillon, would it be OK to [also catch](https://github.com/ocsigen/ocsigenserver/blob/122129bcf8cf70b791b06eda4024bdb50ef31d9c/src/server/ocsigen_socket.ml#L45) `Unix.EADDRINUSE` when we try to open an IPv6 socket? That would make Ocsigenserver work out of the box on WSL, as far as I can tell.
