### ISSUE TITLE
corrupted tarball for ocsigenserver 3.0.0

### ISSUE THREAD

**Issue by mseri** [ocsigen/ocsigenserver#216]
CI tests on the opam-repository involving version 3.0.0 are failing with
```
OpamSolution.Fetch_fail("https://github.com/ocsigen/ocsigenserver/archive/3.0.0.tar.gz (Bad checksum, expected md5=ffb5745d04abd4e2628dc5fe3ccbb89e)")
```
Do you have a way to reupload the original tarball?

**Comment by ilankri** [comment]
Hello,

The command:

```sh
curl --verbose https://github.com/ocsigen/ocsigenserver/archive/3.0.0.tar.gz
```

gives the following interesting information:

```
< HTTP/2 300 
the given path has multiple possibilities: #<Git::Ref:0x00007f9c4b713628>, #<Git::Ref:0x00007f9c4b710fb8>
```

The problem comes from the fact that there is a branch and a tag having the same name `3.0.0` in this repository.

There is a PR to make `opam-publish` produce a more robust `opam` file to support this kind of situation: https://github.com/ocaml-opam/opam-publish/pull/135.

In the meantime, renaming the branch `3.0.0` should do the trick.

**Comment by ilankri** [comment]
> In the meantime, renaming the branch `3.0.0` should do the trick.

Done.

**Comment by mseri** [comment]
Indeed now it works! Thanks
